### ISSUE TITLE
Fixing Colour Contrast

### ISSUE THREAD

**Issue by camelPhonso** [fac27/agency-website#58]
Running Lighthouse on your page currently gives a score of 100 for accessibility (nice one) but there are a few issues that can be seen while navigating.

### Quick win:
What first raised a question for us was the colour contrast on some of your text. The navigation bar particularly gets difficult to read when you hover above the different buttons and the text turns white, blending into the background. Some text showing over the graphics of the page is also quite difficult to understand.

Your README file, which is super complete and really impressive, shows a ticked point for guaranteeing good colour contrast, which makes us thing you considered it done after running lighthouse. Just keep in mind that it can be an uncertain tool sometimes and try to test in different ways.

**Comment by eliazzo** [comment]
Change hover text colour nav bar
