### ISSUE TITLE
refactoring main.js

### ISSUE THREAD

**Issue by camelPhonso** [fac27/agency-website#59]
Your code on script.js is straight to the point and easy to read apart from a few simple details:

- the regex you're using to check the email entry is kind of scary to look at, you can get the same effect with a good use of some flags and special characters. The Execute Program course on regex can help a lot with this ;)
- super detailed comments can be really helpful when you are working on something but they clog up the page and make the code base a bit daunting. With careful naming and a clear structure your code can explain itself and in a future job you'll definitely be advised to do away with verbose comments
- I was confused by the argument in your function submitThis(event). event isn't really being referred when the function runs so it looks like it could have been submitThis(). I wonder if this was left behind from an earlier version of that function ?
- Similarly, console.logging the result of submitThis() won't really do anything but it means you are one step away from being able to show off that function. Maybe you could just include the name on your confirmation message or something, to show the info is being processed ??

**Comment by malcolmwilson8** [comment]
Thanks for the feedback Alphonso! I have decided to pare back the JS a bit and make it simpler. Now it relies on the HTML input fields to prompt users to enter text, and displays the users' name using template literals after they submit.
